### ISSUE TITLE
Xolotl Warrior availability for Mayans

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#103]
I am using your tech tree dataset in my app and I got the feedback that the Xolotl Warrior is currently available for all meso civs. However Mayans cannot create it, because they don't have redemption to convert stables.

It is an edge case but can it still be implemented?

**Comment by simonsan** [comment]
Hmm, but Mayans can get in for example on MegaRandom/HyperRandom when spawning with a stable no?
