### ISSUE TITLE
Houfnice does 55 attack damage to undefined unit/building under advanced stats

### ISSUE THREAD

**Issue by drpeabody** [SiegeEngineers/aoe2techtree#104]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/20492931/148955009-cce58bc1-fdc0-4a39-bebf-1f7d71af1f22.png">

**Comment by HSZemi** [comment]
Thanks for spotting that! Turns out we were missing the dedicated Hussite Wagon armour class. Fixed in bcb5b1e28d19e7561627eeb9597c73b2e48eb428
