### ISSUE TITLE
Units with ability to charge stats

### ISSUE THREAD

**Issue by LOSER4ever** [SiegeEngineers/aoe2techtree#107]
Hey, so there are 4 types of charged stats in the game (we only see 3 of them though).

1. Attack - Coustilliers
2. HP
3. Charge Area attack - Urumi Swordsmen
4. Agility - Shrivamsha Riders

Note that the Charge stats of SVR are different from others because it works even if the charge bar is not full. Also the stats show the max charge, charge time and recharge rate. Clearly one of them is unnecessary since the other two can calculate that.

Minor changes suggested - if charge event = 1 (works only when charge bar is full), show charge time, else show recharge rate. Show max charge in both cases.

**Comment by HSZemi** [comment]
We calculate and display recharge duration as an act of kindness, since it's probably easier to process than the combination of max value and recharge rate.
