### ISSUE TITLE
Monks

### ISSUE THREAD

**Issue by LOSER4ever** [SiegeEngineers/aoe2techtree#109]
Hey, I noticed that Monks show a 1 s reload rate, which is what is present in the stats. But the charge of monks works differently. It takes 100/Resource 35 seconds for a monk to regain the faith. Resource 35 states the recharge rate for a monk, just like how we can see recharge rate of coustilliers, SVRs, etc.

Also, I noticed that Illumination recharges faith 87.5% faster, not 50% faster. Illumination adds 1.4 to Resource 35, which is 1.6 by default. 1.4/1.6 = 0.875 = 87.5%, for the maths. I am gonna report the issue to the devs too.

**Comment by HSZemi** [comment]
Isn't the reload rate simply responsible for how frequently the monk checks whether a conversion succeeds?
https://www.youtube.com/watch?v=-qRUaOHpbwI
