### ISSUE TITLE
Sergeant from castle-lane shows its stats from feudal age and not castle age

### ISSUE THREAD

**Issue by SamuelMeilleur** [SiegeEngineers/aoe2techtree#115]
According to the wiki: https://ageofempires.fandom.com/wiki/Serjeant, sergeants have 65HP, 8 attack and 3/3 armor in castle age but it shows the stats from feudal age (45hp, 5 attack and 2/2 armor) for sergeants from the castle .

**Comment by HSZemi** [comment]
Looking in AGE3, that is actually an effect of Castle Age.
![grafik](https://user-images.githubusercontent.com/3027817/218518224-345b3de9-ac22-45d6-b9a3-a77363b49acf.png)
This means that the "wrong" stats of the Serjeant are sadly an artifact of the fact that we currently don't replicate the effects of techs, civ bonuses and team bonuses in the tech tree.

**Comment by SamuelMeilleur** [comment]
In this case specifically, since you show serjeant in donjon-lane and castle-lane, I thought it could be possible to reflect the feudal-age stats in the donjon-lane and teh castle-age stats in the castle-lane.

**Comment by HSZemi** [comment]
Well, those _are_ the base stats of the Castle Serjeant in the Castle lane :shrug:

**Comment by SamuelMeilleur** [comment]
I get what you mean, I was just confused for a sec until I checked the wiki because I got the impression from the website that sergeants in castle-age would have 45hp instead of 65hp. I'll close the issue if you want to keep it like that.

**Comment by HSZemi** [comment]
Well, I don't want to keep it like that. It definitely makes more sense to display the actual HP value that you encounter in-game. However, I don't currently have the capacity to implement a sustainable general solution that can accomplish this.
