### ISSUE TITLE
Sicilians bugged

### ISSUE THREAD

**Issue by zamir0109** [SiegeEngineers/aoe2techtree#117]
Hi, after new patch update, Sicilians tech tree is not shown in the page. Tried multiple languages but the error persists.

## Steps to reproduce:
- Select Sicilians in the dropdown list 
- Or enter https://aoe2techtree.net/?lng=en#Sicilians

**Comment by HSZemi** [comment]
Looks like I forgot to add the Spearman line to the Donjon. Sorry about that! Should be fixed with a6884725826978f99ece2735adff880c204a2b67
