### ISSUE TITLE
Shotel/Camel "undefined" armour, Cavalry "undefined" attack seems to be for Royal Heirs

### ISSUE THREAD

**Issue by Arxian** [SiegeEngineers/aoe2techtree#118]
May be known already and an issue is maybe not the best way to communicate this, but it looks like the new attack class added to mounted units and armour class added to Shotels and Camels is to enable the new functionality of the Royal Heirs UT, which I imagine will increase that AC by 3.

**Comment by HSZemi** [comment]
Thank you for your message! This is actually an excellent way to report issues. The missing classes have been added.
