### ISSUE TITLE
Repeatable confusion

### ISSUE THREAD

**Issue by chromy** [SiegeEngineers/aoe2techtree#122]
I noticed Spies/Treason shows up as 'Not repeatable':

<img src="https://user-images.githubusercontent.com/351085/237059784-b0db9705-32cc-463c-ad97-4e804c083b79.png" width="300">

I guess the situation is a bit complicated there as iirc Spies can only be researched once whereas Treason can be researched multiple times. Then I noticed that many of the castle techs (conscription, hoardings, etc) claim to be repeatable: 

<img width="300" alt="Screenshot 2023-05-09 at 10 53 02" src="https://user-images.githubusercontent.com/351085/237061187-3e3a6343-5f05-442f-bf49-b05d9abad604.png">

When I don't believe they are. Initially I thought the sense of the boolean was swapped but then looking more I found cases like this:

<img width="300" alt="Screenshot 2023-05-09 at 10 53 02" src="https://user-images.githubusercontent.com/351085/237062239-ef5382b8-83d9-4ea8-a89d-78a9654a033b.png">

<img width="300" alt="Screenshot 2023-05-09 at 10 57 47" src="https://user-images.githubusercontent.com/351085/237062426-31acaaff-7960-408b-976d-88b9e962289a.png">

...so now I'm just super confused about what the meaning of repeatable is. I had a quick look at `generateDataFiles.py` but I didn't have my install of aoe2 on this machine to debug further.

**Comment by HSZemi** [comment]
Oh, hehe. So, a bit of history:

1. Modders make 3x / 9x / 256x tech mods where you can research (most) technologies multiple times in a game
2. AoE2 DE somehow breaks them, especially the 256x tech mods
3. The developers implement an event [cheat](https://ageofempires.fandom.com/wiki/Cheat_codes_(Age_of_Empires_II)) called "going above and beyond" which natively turns on 256x tech mode
4. The developers make that generally available in the game

There are technologies that do a one-time thing which cannot be applied multiple times. Examples are things like Age-Ups (no need to research Feudal Age multiple times) or Ballistics (which just turns a certain behaviour on). Those were not multiplied in the original 256x tech mods, and are also only available once with the cheat.
The `repeatable` flag on a technology determines whether this technology can be researched multiple times with the cheat or just once.
This can also be used in random map scripting by modifying the `ATTR_SET_STACKING` and `ATTR_SET_STACKING_RESEARCH_CAP` values of a technology.

Now. Treason is something completely different. If I remember correctly, it is not actually a technology, but works more like some kind of Patrol command.

**Comment by HSZemi** [comment]
[Sample](https://www.youtube.com/watch?v=VNn2arU-HV8)

**Comment by chromy** [comment]
Ah ha! Thank you 😄
That makes a lot of sense - I just didn't make the connection to Nx tech mods at all.

Thanks for the detailed explanation! :)
