### ISSUE TITLE
Civ bonuses should affect the prices

### ISSUE THREAD

**Issue by keichan34** [SiegeEngineers/aoe2techtree#13]
For example, the Spanish bonus "Blacksmith upgrades don't cost gold" isn't reflected in the tech tree when the Spanish civ is selected.

I understand how conditional bonuses would be hard to implement (for example, having Supplies or not would affect the price of the Militia line), but is this possible for general bonuses for civs like the Spanish or Chinese?

**Comment by HSZemi** [comment]
Does the in-game tech tree do this?

To implement this, for each such bonus we would have to:
- Manually define which units, buildings and technologies are affected by it
- Manually define the modification
- Update those settings every time a balance change modifies the bonus

It certainly sounds doable, but it requires non-negligible effort.

**Comment by keichan34** [comment]
@HSZemi Yeah, taking a look at the code and data I came to the same conclusion. I can't check quickly right now but IIRC it does (I remember checking if the Korean -15% wood bonus applied to the turtle ship in game) 

I'll close this for now. If I get around to it I might be able to send a PR in the future
