### ISSUE TITLE
Separate Tech Tree for Return of Rome Mode

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#131]
Hi, is there any plan to implement a tech tree for the unit of the civs of the return of rome mode (assyrians, etc.)? Just asking because I use the data files and localizations of this project for https://github.com/denniske/aoe2companion and I am wondering if I should incorporate return of rome civs and units in the app and how.

**Comment by HSZemi** [comment]
soon™

**Comment by HSZemi** [comment]
Now :smiley: 
https://github.com/SiegeEngineers/aoe2techtree/tree/master/ror
