### ISSUE TITLE
Camel Rider - Cavalry Resistance - Ethiopians

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#132]
Hi, the camel riders get -3 attack and armor bonus for "cavalry resistance". 

<img width="785" alt="image" src="https://github.com/SiegeEngineers/aoe2techtree/assets/1076211/ac4e3df5-73c6-4ffe-a84e-3e6d2bd01b29">

Does this have anything to do with royal heirs from the ethiopians? Because it is shown for all civilizations.

Just got this question on the discord:

<img width="1167" alt="image" src="https://github.com/SiegeEngineers/aoe2techtree/assets/1076211/a8d6074b-8d9e-4f16-8769-bc6a86bdee5e">

<img width="887" alt="image" src="https://github.com/SiegeEngineers/aoe2techtree/assets/1076211/a4ed4b1d-1a40-43f2-b722-e4ccc115aa43">

**Comment by HSZemi** [comment]
Royal Heirs sets the Cavalry Resistance Armor for Camels and Shotels from -3 to 0 (or rather, adds 3). Afterwards, Camels and Shotels take 3 less damage from cavalry units.
![grafik](https://github.com/SiegeEngineers/aoe2techtree/assets/3027817/f6b374f6-a19c-4838-8284-c958916ab8ed)

**Comment by denniske** [comment]
Ah then everything is correct. Good to hear 👍
