### ISSUE TITLE
Persians parthian tactics should be castle age

### ISSUE THREAD

**Issue by kaysond** [SiegeEngineers/aoe2techtree#138]
Currently under imp:
![image](https://github.com/SiegeEngineers/aoe2techtree/assets/1147328/59095d60-c7d1-4279-8be8-3ec750e71c18)

**Comment by HSZemi** [comment]
Well yes, but no. See https://github.com/SiegeEngineers/aoe2techtree/issues/136

**Comment by kaysond** [comment]
> Well yes, but no. See #136

Yeah I did take a quick look at the data file and noticed it wouldn't be easy. Figured I'd open an issue for tracking anyways...
