### ISSUE TITLE
There is an ‹i› at the end of building descriptions

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#139]
See e.g. `Palisade Wall`

<img width="295" alt="image" src="https://github.com/SiegeEngineers/aoe2techtree/assets/1076211/8d3e126c-73a9-4dd0-9f6f-b5a2d59788fc">

**Comment by HSZemi** [comment]
Yeah, this seems to be an issue with buildings without upgrades, so Palisade Wall, Palisade Gate, and Fortified Wall. The Wonder is also affected because the devs forgot the second \<i> for the upgrades.

Fixed in 11ed51202811f6b928c928bda42e8d289cf804f4, thanks :yellow_heart:
