### ISSUE TITLE
Add other languages

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2techtree#14]
Currently the tech tree is only available in English. We could take the strings files of all available languages and make the tech tree available in those languages as well.

This would mean:
- Increased size of the data file *or* separation of data and text
- Hardcoded civilisation selection dropdown would have to become dynamic
- Anchors should encode the language as well (keep `en` as the default language)

**Comment by HSZemi** [comment]
The value placeholder substitution uses hardcoded english strings, that could be an issue…

**Comment by markoshorro** [comment]
Yes, indeed. However I think it would pay the effort to do that. I do not have very clear though which would be the best way to refactor this.

The kvms2json.py script basically takes the .txt file an generates the .json, so probably in this step we could have a dictionary depending on the language, in order to generate the different locales.

If you are still interested in doing this and you have another better approach, I could help you.

Thanks

**Comment by pardoman** [comment]
Btw, I'm taking a stab at this issue. I have a fork with my WIP, mostly focused on the localization infrastructure: https://github.com/pardoman/aoe2techtree/tree/pardoman/i18next
I'll avoid UI changes for now

**Comment by pardoman** [comment]
Btw, I favor 

> separation of data and text files.

Also: 

> Hardcoded civilisation selection dropdown would have to become dynamic

is done in the branch, but would need some re-work once the data and text files are implemented.

**Comment by pardoman** [comment]
PR ready 🎆

**Comment by pardoman** [comment]
New PR ready

**Comment by NicolasERT** [comment]
Very good repository. I have found inconsistencies in the translation files in the branch "all-locales-2", eg 26288 should be Konnik, but in the MX files you will find elite konnik. The same in 26290 should be elite konnik, but there is the keshik in MX.
There may be more, they are the ones I have found.

**Comment by HSZemi** [comment]
A language switcher has been added :tada: 

The inconsistency with the Konnik texts does actually stem from the original game files, so it's up to Forgotten Empires to fix those :grimacing:
