### ISSUE TITLE
How do I add: custom units, buildings, and technologies?

### ISSUE THREAD

**Issue by ElGoncen** [SiegeEngineers/aoe2techtree#143]
I'm making a mod where I include technology, buildings and units of my own. I wanted to use this script to be able to put everything included in my mod on my website. I have figured out how to enable and disable units, technology and buildings, as well as modify descriptions to add new Civilizations by modifying the "generateDataFiles.py" but I have not understood how to add units, buildings and new technologies and how to link them together. I have little programming knowledge, so I would greatly appreciate the help

**Comment by HSZemi** [comment]
The buildings, units, and technologies are organized into lanes. The lanes are being filled [here](https://github.com/SiegeEngineers/aoe2techtree/blob/master/js/techtree.js#L728), and the connections between panels are being defined [here](https://github.com/SiegeEngineers/aoe2techtree/blob/master/js/techtree.js#L1069).

**Comment by ElGoncen** [comment]
Thank you

It helped me a lot
