### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Tikey14** [SiegeEngineers/aoe2techtree#144]
Hello,

The current tree its outdated, for what I see, its missing two updates

https://www.ageofempires.com/news/age-of-empires-ii-definitive-edition-update-111772/
https://www.ageofempires.com/news/age-of-empires-ii-definitive-edition-update-preview-125283/

It's a cool website, it would be awesome if we could get it up to date.

**Comment by HSZemi** [comment]
Hm. It looks like I mistakenly referenced Update 108769 when I added the changes for Update 111772. Oops!
As for Update 125283, I'll add it without the Chronicles civs first. Will have to think how to incorporate them.
