### ISSUE TITLE
Concentrate data

### ISSUE THREAD

**Issue by Maxzor** [SiegeEngineers/aoe2techtree#23]
Hello, nice endeavour thank you :)

You extract data/data.json from dat files.
But reverse-engineered js/civs.js right? What about putting the civ/tech-tree-disable map in a json file too ? js folder was the last directory I was expecting finding such data.
I am considering flattening into a multi-civ tech chart like those ancient ones did (is there really no such one for DE? Dayum they just milking the cow...):
https://www.redbubble.com/people/mammothtank/works/29656608-age-of-empires-2-civilization-tech-tree?p=poster

**Comment by Maxzor** [comment]
Found my happiness with JSON.stringify(civsConfig) in firefox js console.
If you are interested in such a chart I can dedicate time to PR.
BR

**Comment by Maxzor** [comment]
A quick and dirty way with JSON.stringify in firefox console, thinking atm of a micro-sqlite to play me some theorycraft :)

**Comment by HSZemi** [comment]
We currently use constants (defined in `techtree.js`) instead of raw strings for names, which enables us to fix typos and do renamings at a central place and with IDE support. That would unfortunately not be possible with a json file.

Ideally one would extract the tech tree info from the dat file as well, but I have not yet managed to do that.

**Comment by Maxzor** [comment]
Has anyone already managed to get the full .dat in human-readable form?
https://github.com/sandsmark/genieutils/issues/6

**Comment by goto-bus-stop** [comment]
the dat file is a pretty big heap of binary data. it could be output into a "human-readable" format like JSON but it would likely be in the hundreds of megabytes, so it would not really be easy to find anything still :)

**Comment by Maxzor** [comment]
I agree that json probably wouldn't be the best format.
The amount of data does not matter much, uncompressed the main dat file is 22MB : what matters is its structure and its obfuscation.

**Comment by goto-bus-stop** [comment]
22MB of binary data becomes much much more when you turn it into a human-readable form 🙂

The file format is known. Genieutils contains the most complete reader for it. The openage converter also supports most if not all of it, and actually outputs to CSV formats.

**Comment by Maxzor** [comment]
I am into relational databases so data size is really not an issue :)
What is giving me trouble is finding a way to 'fully unzip' game data files esp. .dat.
Genieutils and age3 are especially lacking in this domain for reverse-engineer profanes.

**Comment by goto-bus-stop** [comment]
tbh, I'm not sure what you're looking for…After decompressing a dat file, you can not "unzip" it any further, you can only interpret the data, which is what genieutils does. If you want to put dat file data into a relational database, the best way to do it would be to write a C++ program that uses genieutils to read the dat file into C++ data structures, and uses whatever API your database provides to write them into that database.

**Comment by Maxzor** [comment]
you can only interpret the data : this is were I am having issues. Thank you for hints already

**Comment by HSZemi** [comment]
Looks like you have been helped and there is nothing to do for us here, I will close this issue then.
