### ISSUE TITLE
URL only support first letter as Capital (Chinese, not chinese)

### ISSUE THREAD

**Issue by ia5634** [SiegeEngineers/aoe2techtree#28]
The problem is you can view the specified civ info if you type first letter in UPPER CASE like "Chinese".

If you type in full lower case like "chinese" after "#" the website show "Aztecs".

If you can change letter to lowercase it'd very useful for common using.

Thanks.

**Comment by HSZemi** [comment]
I am not sure why you would ever want to type the hash yourself, since you can just select the civilisation with the dropdown and then copy the URL.

Anyway, I hope 1b5335ef210b366fd8a927aec87df1e1d1ebe68b fixes your issue :+1:
