### ISSUE TITLE
Make cross reference UI collapsible

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2techtree#31]
I would really like to have the collapsable cross reference UI!

Currently, the panel is so tall that it overflows my screen:
![image](https://user-images.githubusercontent.com/2985436/77892399-6dd22100-7227-11ea-8119-979a2dd7973a.png)

The other option is just fixing the code that positions the help panel. Either options would result in a great outcome imho. Cheers~

_Originally posted by @pardoman in https://github.com/SiegeEngineers/aoe2techtree/pull/15#issuecomment-605863793_

**Comment by HSZemi** [comment]
The solution seems obvious: We need to crowdfund a bigger screen for @pardoman :smile: 

It sounds like a sensible feature, I just do not know yet what would look best UI wise. Suggestions?

**Comment by goto-bus-stop** [comment]
Don't know how you feel about taking on dependencies, but it might be an idea to use [popper.js](https://popper.js.org/). Getting popover positioning right is difficult, and that package is widely used for good reason :)

**Comment by HSZemi** [comment]
I tried using popper.js for positioning, but it did not want to fully cooperate with me. The resulting positions seemed quite jumpy. I would still like to thank you for the recommendation, though.

[In the end](85871f33d01082ed20b24fd35c0a656eb985ee1d) I just modified the existing positioning algorithm (not recommended by the experts, I know) and hope the result is at least "good enough".

**Comment by pardoman** [comment]
I support having a solution that doesn't rely on yet-another-dependency. Thanks @HSZemi
