### ISSUE TITLE
data reference ID in the json

### ISSUE THREAD

**Issue by markus7h** [SiegeEngineers/aoe2techtree#34]
to build an analytic dashboard it would be great if the json could contain reference id's. ie. what unit belongs to what civ and what building can create what unit. It is somewhere in the scripts, of the html page, for me a little difficult to rebuild

**Comment by HSZemi** [comment]
I think the information you are looking for is contained in `techtree.js` and `civs.js`. The reason for this is that we have not yet managed to extract that information from the gamedata automatically, unlike the data in the json files.

**Comment by markus7h** [comment]
Yes You are right, that looks like what I am looking for. Thank You
