### ISSUE TITLE
Unique techs unlocked for every civ

### ISSUE THREAD

**Issue by AugustoXDBR** [SiegeEngineers/aoe2techtree#36]
Every unique tech shows as if owned by every civilization. 
![like here](https://user-images.githubusercontent.com/58894348/80297848-68e88a80-875d-11ea-932a-50b4212b90b4.png)
![or here](https://user-images.githubusercontent.com/58894348/80297858-76057980-875d-11ea-8c0c-8774cd5ffa12.png)

**Comment by HSZemi** [comment]
That is true, I am honestly more surprised that that is not the case for the unique units. Maybe I can transfer some logic over.

**Comment by HSZemi** [comment]
Found it! 59fa1811ce69dc4f94941d6b7ab097dc24e32afa
Thank you for the bug report.

**Comment by AugustoXDBR** [comment]
Nice! Glad to see it fixed. Couldn't even come back home in time to see it.
