### ISSUE TITLE
Add extra details?

### ISSUE THREAD

**Issue by willemmulder** [SiegeEngineers/aoe2techtree#37]
Hi, I'm trying to use the data.json to make a simulator. 
That works great, so thanks! 
But it could be even better when I had a few extra details.

I don't know which data is available exactly through the .dat file but could it be possible to add some of the below details to data.json?

Things I encountered so far:

- Projectile speed
- 'Frames per Angle' and 'Animation Duration' to properly calculate the Frame Delay in seconds
- Monk conversion 'susceptibility' per unit
- Blast Radius
- Trample Damage

And probably more complicated (?):

- Structured data around technologies and upgrades, e.g. "Plate Barding Armor" : { targetClass: "cavalry", upgrades: { "meleeArmor" : 1, "pierceArmor" : 1 } } 
- Maybe break out the consts (e.g. const UNIQUE_UNIT = "UNIQUE UNIT";) into a separate JS file?

Thanks!

**Comment by HSZemi** [comment]
What you are asking for sounds a bit out of scope for the tech tree and should probably rather be done in [aoe2dat](https://github.com/HSZemi/aoe2dat)

**Comment by willemmulder** [comment]
Ah good point. 

However for me the data format of this data.json is much more useful than the JSON's from aoe2dat. The full JSON is too big (for use on a website, that is), while the units_buildings_techs.json is 'too small' in that it does not have things like armor classes. 

Do you know whether the info I'd like to have is actually in the full.json? Because if so, I should maybe write a pre-processor that outputs the desired data for me...

**Comment by HSZemi** [comment]
The tech tree's `data.json` is generated from `full.json`. You can check [scripts/generateDataFiles.py](https://github.com/SiegeEngineers/aoe2techtree/blob/master/scripts/generateDataFiles.py) to see how that is done.

**Comment by willemmulder** [comment]
Well then, let's see if Nodejs handles that equally well and try it out for myself :-) Thanks a bunch!

Oh, and if you'd consider to add a few extra properties to the units_buildings_techs.json, that would be awesome as well!

**Comment by willemmulder** [comment]
I've just successfully written a full.json parser based on the file you mentioned. Thanks again!
