### ISSUE TITLE
New UI Background

### ISSUE THREAD

**Issue by umutbalkan** [SiegeEngineers/aoe2techtree#40]
Something is off with the rows of tech tree and the background image. I'm using Microsoft Edge as the browser (it was working well a couple of days ago).

![aoe2tech](https://user-images.githubusercontent.com/8284138/81017297-ce79fc80-8e6a-11ea-8336-0635520f539d.PNG)

**Comment by HSZemi** [comment]
Does it always look like that for you?  
I was noticing a similar phenomenon on my machine sporadically, but blamed it on an issue with my graphics card.

**Comment by umutbalkan** [comment]
found the error https://github.com/SiegeEngineers/aoe2techtree/commit/0283c2cce9d3042cf4223557859be4a01f8039a6#r38942068

**Comment by HSZemi** [comment]
Looks like Edge does not like alpha values :shrug: 
I am trying other solutions at the moment. Should be fixable :+1:
