### ISSUE TITLE
Fonts not looking great

### ISSUE THREAD

**Issue by pardoman** [SiegeEngineers/aoe2techtree#45]
Hey, I tried the app today and noticed that the fonts for the CivTree are getting rendered outside of their respective squares. See `Elite Skirmisher` or `Man-at-Arms`.

![image](https://user-images.githubusercontent.com/2985436/81254030-dc508e80-8fde-11ea-8c17-adb1551144a9.png)

I'm on a MacBook Air, running Chrome 81.

Similar issue in Firefox Developer Edition version 77.0b2
![image](https://user-images.githubusercontent.com/2985436/81254248-70baf100-8fdf-11ea-8c30-a16783ecaee0.png)

**Comment by HSZemi** [comment]
@lalitpatel Would you like to have a look at that?

**Comment by HSZemi** [comment]
My guess would be that this is an issue with smaller screens – the rectangles get scaled down while the font does not.

Here I overlaid a screenshot from my pc with pardoman's provided screenshot. The text matches exactly, but my (transparent) rectangle is bigger than pardoman's (solid) rectangle.
![image](https://user-images.githubusercontent.com/3027817/81406209-74628b00-9139-11ea-9527-4155605c3f32.png)

@pardoman what is your screen resolution? Mine is 1920x1080.

**Comment by pardoman** [comment]
My resolution is 1440 x 900 on a 13.3 inch display.

**Comment by HSZemi** [comment]
There might be a solution to this. Currently, we're scaling UI elements depending on the available vertical space, but we neither scale horizontally, nor do we scale the font sizes. That has the advantage that the text stays at a legible size even if there is only little vertical space, but of course it falls out of the rectangles.

We could employ an entirely different approach: Create the full tech tree svg at a fixed size, and then scale the entire thing (preserving the ratio) to fit the available vertical space. That way, the text size should also get scaled and the text should stay inside of the rectangles.

Any thoughts / pros / cons on that approach?

**Comment by pardoman** [comment]
Sounds good as long as the text doesn't blur too much due to the scale-down.

**Comment by pardoman** [comment]
Btw, fonts are looking much better now:

![image](https://user-images.githubusercontent.com/2985436/81743791-1beffe00-9457-11ea-8460-2c57f5d34df9.png)

I'm closing this issue.

**Comment by HSZemi** [comment]
But I didn't do anything in that direction :sweat_smile:

**Comment by lalitpatel** [comment]
> We could employ an entirely different approach: Create the full tech tree svg at a fixed size, and then scale the entire thing (preserving the ratio) to fit the available vertical space. That way, the text size should also get scaled and the text should stay inside of the rectangles.

Hi @HSZemi and @pardoman Sorry for being MIA; had to take care of some personal stuff.

I have noticed the same in smaller screens. The primary reason is the height of the viewport. The approach you suggested would make the text so small in smaller screens that it wont be legible.

My proposal is not to scale the unit boxes but scale the horizontal white space between the unit boxes. So for a screen of lower viewport height, it would appear as the ages are more tightly packed / compressed but would preserve the legibility and the text wont overflow the unit boxes.
