### ISSUE TITLE
DE building ordering

### ISSUE THREAD

**Issue by yeah-toast** [SiegeEngineers/aoe2techtree#46]
Hi there, I noticed a few discrepancies in ordering between the Definitive Edition in-game tech tree and the site, most of which are due to differences between the DE and HD tech trees. 

- Blacksmith/Siege Workshop have moved to between the Stable and Dock, from between Town Center and University in HD.  Internal to this, Mangonels and Rams are reversed under Siege Workshop -- in both HD and DE they are consistent with their position in the building menus where Rams are on the left.
![20200507162250_1](https://user-images.githubusercontent.com/64550130/81353947-3acd4980-907f-11ea-813d-ad4b93ca284d.jpg)

- The University is now between the Dock and Towers, instead of Blacksmith and Mining Camp in HD.
![20200507163113_1](https://user-images.githubusercontent.com/64550130/81354406-5be26a00-9080-11ea-8313-3d9fa3d5bebe.jpg)

- The Wonder (and Feitoria on the Portuguese tree) are now between Town Center and Mining Camp instead of between Stable and Dock in HD.
![20200507162306_1](https://user-images.githubusercontent.com/64550130/81353951-3ef96700-907f-11ea-871f-bf06b7585b88.jpg)

- Krepost is found between Castle and Monastery on the Bulgarian tech tree, rather than between Stable and Dock, and it shows the Konnik as a buildable unit.
![20200507162316_1](https://user-images.githubusercontent.com/64550130/81353961-43258480-907f-11ea-9469-e3fc305e2769.jpg)

These are rather minor issues I know, but the Blacksmith/University ordering in particular really throw me off whenever I switch between the website and game trees.  I'd totally understand if you're keeping it this way to match HD Edition, however since the dataset is based on the latest version of DE, I figured consistency in alignment would make the most sense.  Anyway, love the site - keep up the good work!

**Comment by HSZemi** [comment]
A sensible proposal.  
I expect the Konnik under the Krepost to pose a little challenge (similar to the second Town Center).  
We shall see when I'll find the time to implement this change, but a pull request is equally welcome of course.
