### ISSUE TITLE
[Request] Add a setting to display "Advanced Stats" by default

### ISSUE THREAD

**Issue by tylerfehr** [SiegeEngineers/aoe2techtree#47]
Most of the time I reference the site, advanced stats are what I'm looking for. This behavior was default before the caret markers were added to expand the entity description window.

![Advanced stats are now hidden until you click the arrow marker](https://user-images.githubusercontent.com/56086429/81506258-96e4d780-92e4-11ea-9ce6-b710b24459f7.png)

![the UI setting could be here or above the 'key'](https://user-images.githubusercontent.com/56086429/81506333-11155c00-92e5-11ea-9bf3-bc641b3e9ed3.png)

**Comment by HSZemi** [comment]
I think there is no need for an explicit setting. In 0de9bd7d386d86b7cd07369032864fa9bd1b0daa I simply made it remember the toggle state of the advanced stats. This means if you show the advanced stats and then visit the page again later, they will be shown by default until you hide them again (or until localStorage is wiped).

**Comment by tylerfehr** [comment]
Wasn't aware of that. Thanks for the info!

Closing now.

**Comment by HSZemi** [comment]
You could not have been aware of it since I just added this functionality after seeing your request. No worries!
