### ISSUE TITLE
Can we put drop down in the same position as in-game tech tree?

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#5]
Put it in the position where the civ name is at the moment,

I would provide pull request if needed.

**Comment by HSZemi** [comment]
Do you mean:
1. add an additional dropdown, or
2. move the existing dropdown?

Case 1: I do not really see a benefit of a second dropdown a few centimeters from the current one. It would also introduce overhead to synchronize the two dropdowns (which would not be too difficult though).

Case 2: The current dropdown position has the benefit that it is possible to switch the civilisation while having scrolled to the right. If the dropdown got moved to the position you suggested, one would have to scroll back to the very left, change the dropdown, and then possibly scroll back to the right.

You can check out https://aoe2techtree.com/ though, they have the dropdown in the position you suggest.

**Comment by denniske** [comment]
I wanted to suggest case 2, but now I think case 1 would be a good idea. Then it is easy to find the drop down and choose a civ when you first visit the page. And afterwards if you scrolled in the tree you can use the fixed drop down. Maybe put the fixed drop down in the top center?

Another idea would be to make only the right part scrollable and keep the civ info box fixed on the left side. What do you think about that?

**Comment by HSZemi** [comment]
Keeping the civ info visible while scrolling the tech tree could actually be nice and work out well.
