### ISSUE TITLE
[Bug] Displaying unique buildings for all civs

### ISSUE THREAD

**Issue by AugustoXDBR** [SiegeEngineers/aoe2techtree#50]
Both the default disabled buildings (Feitoria and Krepost) show as available for all civs.
![Screenshot_47](https://user-images.githubusercontent.com/58894348/81724798-578cc700-945b-11ea-92c9-ddb934769e80.png)

**Comment by HSZemi** [comment]
Oops. That was a bug indeed. It should be [fixed now](b01f28caf4ad38c4fadb8582ae5e11cf0a903276). Thank you for the bug report!

**Comment by AugustoXDBR** [comment]
Nice! Glad to help with at least the reportagem.
