### ISSUE TITLE
Page display techtree

### ISSUE THREAD

**Issue by zonton** [SiegeEngineers/aoe2techtree#51]
Hey guys, i got an issue as i tried to watch the AOE 2 Tech tree on internet, both on my computer and on my mobile phone. I can't see the top of the page and so i can't change the civs and can't see all the feodal age possibilities. 
I tried to use an other research engine, didn't changed anything. 
Love the work you do btw !
New on GitHub so don't be mean ;)

**Comment by pardoman** [comment]
I was able to repro this. If the screen's resolution is not high enough, then something like this might happen:
![image](https://user-images.githubusercontent.com/2985436/81743705-f236d700-9456-11ea-8085-78ffafe2522c.png)

**Comment by HSZemi** [comment]
I feel like there was an influx of similar reports recently. I would have blamed it on the newly added key and reverted that, but on @pardoman's screenshot it looks like that is not the culprit :thinking:

**Comment by HSZemi** [comment]
@zonton @pardoman I just pushed an update, could you check if the worst issues are resolved now?

**Comment by zonton** [comment]
The issue seems to be resolved as far as i can see. 
At least on my computer !
If you need one more screenshot say it :)

**Comment by zonton** [comment]
Great work :+1:

**Comment by pardoman** [comment]
Works great now, thanks. Feel free to close.
