### ISSUE TITLE
Xolotl Warrior missing

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#62]
The Xolotl Warrior is missing in the tech tree:
[https://ageofempires.fandom.com/wiki/Xolotl_Warrior](https://ageofempires.fandom.com/wiki/Xolotl_Warrior)

It is not a much used unit but it may be worth to include it for completeness.

**Comment by HSZemi** [comment]
So we would have a unit below the stable that is available if and only if the stable is not available? Sounds fun.

**Comment by HSZemi** [comment]
Here we go 1d42c1ae90bda676192bbb92ecbe6fb7021c9461
