### ISSUE TITLE
Show cost for Elite unit upgrades

### ISSUE THREAD

**Issue by ruudvan** [SiegeEngineers/aoe2techtree#66]
It would be nice to see the cost of the Elite upgrades for units. Right now unique units, eagles, skirms, etc. have the stats of the Elite unit listed. There's no way I could see to get the cost of the upgrade. 
Maybe like the in-game tech tree, it lists the upgrade cost at the end of the Elite unit description.

**Comment by HSZemi** [comment]
I am not sure what information exactly you are missing.
![grafik](https://user-images.githubusercontent.com/3027817/88703137-9fdb8d00-d10c-11ea-87cb-4b3f19176fb6.png)

**Comment by ruudvan** [comment]
My apologies. I was looking at the elite unit description to figure out the cost. Please close this.
