### ISSUE TITLE
Konnik mounted/dismounted

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#67]
I have found some differing stats for the **Konnik mounted vs. dismounted** in the AoE II wiki:
[https://ageofempires.fandom.com/wiki/Konnik](https://ageofempires.fandom.com/wiki/Konnik)

E.g. pierce armor:
1, 2 (Elite)
0, 1 (Elite) (Dismounted)

In the tech tree the pierce armor of the **mounted Konnik** seems to be used.

Are there maybe two units in the AoE II Dataset? One for the mounted and one for the dismounted Konnik?

This would also be interesting for implementation of counter units of the different Konnik versions here:
https://github.com/denniske/aoe2companion/issues/10

**Comment by HSZemi** [comment]
Konnik (ID 1225/1254) and Dismounted Konnik (ID 1252) are two distinct units. The Dismounted Konnik is set as the `dead_id` of the Konnik. That's how the "dismount" works. It's the same for the Elite versions (IDs 1227/1255 and 1253)

I would like to have the stats of the Dimounted Konnik in the tech tree as well, but sadly that seems to require a lot of custom logic, which is quite unfortunate.

**Comment by denniske** [comment]
Do you know why there are two IDs for the mounted Konnik (1225/1254) although they have the same content?

Can you include the IDs 1252 and 1253 for the dismounted Konnik in /data/data.json even though you don't use it? This would be easier for me to embed it into aoe2companion.

**Comment by HSZemi** [comment]
I don not know, but I am fairly certain it is due to the (Elite) Konnik being available in the Castle as well as in the Krepost. There are also two instances of (Elite) Huskarl and (Elite) Tarkan.

Adding the data for the dismounted Konnik should be possible.

**Comment by HSZemi** [comment]
Here you go: 6367b08868ebf4695c8b122cb541a6fcb8abdc78
