### ISSUE TITLE
What does HD Camel stand for?

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoe2techtree#68]
I got a question from a user of my app:
"What’s the hd stand for in hd camels. +3 damage only against camels with high definition, low graphics camels will not be effected? :joy:"

https://github.com/SiegeEngineers/aoe2techtree/blob/master/index.html#L140

Is the HD referring to the AoE HD version? It can probably renamed to just "camel", right?
https://ageofempires.fandom.com/wiki/Armor_class:_Camel

**Comment by HSZemi** [comment]
See here: https://github.com/Tapsa/AGE/blob/master/AGE_Frame/Other.cpp#L700

**Comment by denniske** [comment]
Thx :) So it is probably because it was introduced in HD version. I will rename it in the app to "Camels".
