### ISSUE TITLE
The Extra Stats No Longer Appear

### ISSUE THREAD

**Issue by schuman-aaron** [SiegeEngineers/aoe2techtree#7]
The movement speed, attack bonuses, attack rate, attack delay, build time, LOS, and time to build no longer appear after selecting a unit. 
OS: W7
Browser: Vivaldi

Please see the image attached below for more details.
![image](https://user-images.githubusercontent.com/7083776/71054096-a63d6b80-211e-11ea-970e-1100874993ef.png)

[Edit]: Only the bonus attacks no longer appear now.

**Comment by HSZemi** [comment]
There were placeholders for those values in the stings from the extended help mod, but they are not in the strings from the original DE files which are currently used due to the lack of an extended help mod for DE (?)

**Comment by schuman-aaron** [comment]
So, are there any plans to resolve this? Are you planning on waiting for the extended help mod to make it's way to DE or is this a "won't fix" problem or what?

**Comment by HSZemi** [comment]
That depends. It seems like there is no extended help mod for DE [currently](https://www.reddit.com/r/aoe2/comments/exulg9/is_there_some_maximum_extended_help_mod_for_de/). We could instead append additional placeholders at the and of the official strings, so that the values appear again. I might try that out actually.

**Comment by HSZemi** [comment]
Looks like it worked. What do you [think](https://aoe2techtree.net/)?
Attack bonuses are still missing since they are a tiny bit trickier, but adding those values looks totally doable as well.

**Comment by schuman-aaron** [comment]
Different, but something I can get used to.

**Comment by HSZemi** [comment]
e85b6039c2538d12bd684f973c0fde4860625a4e added the detailed attack and armour values. Is anything else still missing now?

**Comment by HSZemi** [comment]
In the hope that the answer is "no", I will close this issue for now.
