### ISSUE TITLE
JS is completely broken on firefox 68

### ISSUE THREAD

**Issue by StephenLynx** [SiegeEngineers/aoe2techtree#72]
SyntaxError: invalid regexp group civs.js:1:1
ReferenceError: civ is not defined aoe2techtree.net:311:9
ReferenceError: civ is not defined aoe2techtree.net:311:9
ReferenceError: civ is not defined 33 aoe2techtree.net:311:9
ReferenceError: civ is not defined 2 aoe2techtree.net:311:9
ReferenceError: civsConfig is not defined 3 aoe2techtree.net:592:27

Everything is always marked with an X, changing civs doesn't do anything

**Comment by HSZemi** [comment]
I would say upgrade your web browser, it is more than one year old, but I guess that is not possible for some reason?

**Comment by StephenLynx** [comment]
It's the latest version I get on centos 7, which is still supported. Does it hinge on some super modern feature and it's impractical to change so it would support a browser that is not even 2 years old?

**Comment by StephenLynx** [comment]
Despite what the console says, I believe this is the issue:
   const id_regex = /(?<type>.+)_(?<id>([\d]+))_(x|copy)/;
Changing to
   const id_regex = /(?<type>.+)_(?<id>([\d]+))_(x|copy)/;
Would probably fix it.

**Comment by HSZemi** [comment]
I got myself a brand new Firefox 68 and:

> Despite what the console says, I believe this is the issue:
> `const id_regex = /(?<type>.+)_(?<id>([\d]+))_(x|copy)/;`

This is correct.

> Changing to
> 
> `const id_regex = new RegExp(/(?<type>.+)_(?<id>([\d]+))_(x|copy)/);`
> 
> Would probably fix it.

Sadly, it did not fix it. The issue were the named capture groups `?<type>` and `?<id>`, only available starting from Firefox 78. 9f58e548ebfa4aca1ac0c08507036336626b11b2 should hopefully fix this issue for you.

Also, the `opacity` css property that is used to indicate which civilisation has access to a certain tech or unit is only supported starting from Firefox 70, so you are probably still missing out on that feature, but at least the rest should work now.

**Comment by StephenLynx** [comment]
Actually the indication if the item is available or not is working fine. Are you talking about fill-opacity?

**Comment by HSZemi** [comment]
I am talking about these
![grafik](https://user-images.githubusercontent.com/3027817/95381384-5e274980-08e8-11eb-8f8d-cb3e34943462.png)

**Comment by StephenLynx** [comment]
Ah yeah, true.

**Comment by StephenLynx** [comment]
True. What are you using? `opacity` works here. 
![Screenshot from 2020-10-07 17-29-49](https://user-images.githubusercontent.com/33453298/95384277-c3684400-08c2-11eb-965a-3f26905d94db.png)

**Comment by HSZemi** [comment]
Oh my god. It accepts `'0.2'` but it won't take `'20%'` :facepalm:
