### ISSUE TITLE
Possibly wrong stats for Cavalry Archer and Heavy Cavalry Archer

### ISSUE THREAD

**Issue by HeavenlyChorus** [SiegeEngineers/aoe2techtree#73]
The AoE2 wiki shows both CA and HCA has the same Frame Delay of 10: https://ageofempires.fandom.com/wiki/Cavalry_Archer_(Age_of_Empires_II)
https://ageofempires.fandom.com/wiki/Heavy_Cavalry_Archer

But here, the Frame Delay increases by quite a margin from CA to HCA (35 to 46), how?
![image](https://user-images.githubusercontent.com/13861429/97274322-777c3f80-186f-11eb-8ea0-3877bb4ba1dc.png)
![image](https://user-images.githubusercontent.com/13861429/97274337-7ba85d00-186f-11eb-9453-3dcf4dc3c584.png)

**Comment by HSZemi** [comment]
Could you check with AGE which values appear to be correct?

**Comment by HeavenlyChorus** [comment]
> Could you check with AGE which values appear to be correct?

Sorry, the stats are absolutely correct, as I checked AGE.
Looks like the wiki has a calculated version of Frame Delay, instead of raw data.

**Comment by HSZemi** [comment]
:shrug:
