### ISSUE TITLE
Frame Delay should be displayed in seconds

### ISSUE THREAD

**Issue by Harirarn** [SiegeEngineers/aoe2techtree#78]
Currently frame delay is displayed in frames. But different unit animation are done at done at different frame rates. This makes the number quite meaning less. Further most animation were in about 20 fps in the original game and at 60 fps in DE. This also leads to a big disparity between the numbers for both versions. It would be much better if this attack delay is displayed in seconds instead.

**How I find frame delay in seconds?**
I will demonstrate this with crossbowman in AGE.

1. Find crossbowman in Units tab. Note down its Frame Delay (15) and Attack Graphic (693).
2. Go to Graphics tab and find graphic 693. Note down Frames per Angle (30) and Animation Duration (0.7).
3. The attack delay in seconds is then 0.7*15/30 = 0.35.

So crossbowman shoot after 0.35 seconds. In comparison Arbalester has Frame Delay = 20, Frames per angle = 45 and Animation duration = 0.77. This gives animation duration of 0.77*20/45 = 0.342.

This shows that even though crossbowman and arbalester have different frame delay in frames, they are almost same in seconds.

**Comment by HSZemi** [comment]
Thanks for working on this! :yellow_heart:
