### ISSUE TITLE
Missing tooltip data for some DE techs

### ISSUE THREAD

**Issue by kimegede** [SiegeEngineers/aoe2techtree#8]
When clicking on eg. these no info is shown.
* `Kipchack`
* `Steppe Husbandry`
* `Cuman Mercenaries`
 
Goto and click some of these above.
https://aoe2techtree.net/#Cumans

**Comment by HSZemi** [comment]
Looks like this affects all unique units and techs of the new civs.

**Comment by HSZemi** [comment]
It should be fixed now. Thank you for your bug report!

**Comment by kimegede** [comment]
Wow that was really quick! Great work you are doing! :)
Happy New Years btw ;)
