### ISSUE TITLE
Wrong number for Town Center build time?

### ISSUE THREAD

**Issue by FVMVincent** [SiegeEngineers/aoe2techtree#84]
Hi,
as the title says the TC build time in the techtree is stated as 100s.
Other sources like:
https://ageofempires.fandom.com/wiki/Town_Center_(Age_of_Empires_II) or
https://aoe2stats.net/#
say that it should be 150s or 2:30 minutes.

Further suggestions
You could also add the Town Center field in Feudal Age for cumans. Maybe with a note that only one can be build, and the build time is 270s. (I was searching for the cuman TC build time when I stumbled over this).

**Comment by HSZemi** [comment]
Hm, looks like commit ed9d8f25bd282899eceb0f6e63ef7f6472d13bf7 was a lie and we should instead have used id `621` :thinking: 

The increased cuman TC build time is an effect of the civilisation bonus, and therefore hard to include in the static tech tree. The same goes for the availability of a second Town Center and the Siege Workshop in Feudal Age as well as Capped Ram in Castle Age.

**Comment by HSZemi** [comment]
We're using 621 for now, let's see when the next issue pops up :upside_down_face:
