### ISSUE TITLE
Charge attack and cooldown as additional stats

### ISSUE THREAD

**Issue by k-sriram** [SiegeEngineers/aoe2techtree#85]
Maybe you are already working on it but here is an issue for tracking purposes. The Lords of the West expansion introduced the coustillier which has the charge mechanic. This can be displayed in the stats.
This number can be seen in AGE as Max Charge and Recharge Rate. If I get some time over the weekend I shall write a PR to add it.

**Comment by HSZemi** [comment]
Good call. I added it in 08c556ff03f0b3d5b675150fa5b15389deda2a2e. Does that look right to you?

**Comment by k-sriram** [comment]
Yeah. That looks how it should.
